default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  adapter: sqlite3
  <<: *default
  database: storage/development.sqlite3

test:
  adapter: sqlite3
  <<: *default
  database: storage/test.sqlite3

production:
  adapter: postgresql
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
